### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by Kingjosh007** [Fikerte-T/capstone2-countries-facts#21]
We set the kanban board as you can see in [this repo](https://github.com/Fikerte-T/capstone2-kanban)

> We are two working in this group project: [Fikerte-T](https://github.com/Fikerte-T) and [Kingjosh007](https://github.com/Kingjosh007).

**Comment by Dipeshtwis** [comment]
Hi @Kingjosh007 and @Fikerte-T, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [ ] All cards with group tasks in the title should be assigned to someone (it does not matter to whom as students had freedom with that).

![Screenshot from 2021-10-18 20-59-30](https://user-images.githubusercontent.com/22434660/137762791-9088fe29-93e7-4376-b219-902a5eca6757.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
